on:
  push:
    branches:
      - feature/split

name: monorepo

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: yarn

  lint:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - run: ./node_modules/.bin/lerna run lint

  test:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - run: ./node_modules/.bin/lerna run test -- --coverage

  coveralls:
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        package:
          - signpdf
          - utils
          - placeholder-pdfkit010
          - placeholder-plain
    steps:
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          parallel: true
          flag-name: $
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-path: packages/$

  finish:
    needs:
      - lint
      - test
      - coveralls
    if: $
    runs-on: ubuntu-latest
    steps:
      - name: Close Coveralls
        uses: coverallsapp/github-action@master
        with:
          parallel-finished: true
          carryforward: "signpdf,utils,placeholder-pdfkit010,placeholder-plain"
